name: Close PRs

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  close:
    if: github.event.pull_request.user.login != github.repository_owner
    runs-on: ubuntu-latest
    steps:
      - name: Close external pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr close ${{ github.event.number }} --comment "This repository does not accept external pull requests. Please open an issue instead." --repo ${{ github.repository }}
